// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250724135442_FixProductIdGeneration")]
    partial class FixProductIdGeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Core.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Yüksek performanslı dizüstü bilgisayar",
                            IsActive = true,
                            Name = "Laptop Pro X1",
                            Price = 32000m,
                            SKU = "LP-PRO-X1",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ergonomik ve hassas optik mouse",
                            IsActive = true,
                            Name = "Kablosuz Mouse",
                            Price = 850m,
                            SKU = "MS-WL-001",
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 3,
                            Description = "RGB aydınlatmalı, oyuncular için",
                            IsActive = true,
                            Name = "Mekanik Klavye",
                            Price = 2500m,
                            SKU = "KB-MECH-RGB",
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 4,
                            Description = "Canlı renkler ve net görüntüler",
                            IsActive = true,
                            Name = "4K Monitör 27\"",
                            Price = 8999m,
                            SKU = "MON-4K-27",
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 5,
                            Description = "8-in-1 bağlantı noktası adaptörü",
                            IsActive = true,
                            Name = "USB-C Hub",
                            Price = 1200m,
                            SKU = "HUB-USBC-81",
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hızlı veri transferi için taşınabilir SSD",
                            IsActive = true,
                            Name = "Harici SSD 1TB",
                            Price = 3500m,
                            SKU = "SSD-EXT-1TB",
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 7,
                            Description = "Görüntülü görüşmeler için Full HD kamera",
                            IsActive = false,
                            Name = "Webcam 1080p",
                            Price = 1500m,
                            SKU = "WC-FHD-01",
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 8,
                            Description = "7.1 Surround sesli oyuncu kulaklığı",
                            IsActive = true,
                            Name = "Gaming Headset",
                            Price = 2800m,
                            SKU = "HS-GM-71",
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 9,
                            Description = "Fitness takibi ve bildirimler",
                            IsActive = true,
                            Name = "Akıllı Saat SE",
                            Price = 6500m,
                            SKU = "SW-SE-01",
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 10,
                            Description = "Eğlence ve iş için ideal tablet",
                            IsActive = true,
                            Name = "Tablet 10\"",
                            Price = 7800m,
                            SKU = "TAB-10-STD",
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 11,
                            Description = "Modüler ve verimli PSU",
                            IsActive = false,
                            Name = "Güç Kaynağı 750W",
                            Price = 2100m,
                            SKU = "PSU-750W-MD",
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 12,
                            Description = "Yeni nesil oyun ve grafik performansı",
                            IsActive = true,
                            Name = "Ekran Kartı RTX 4070",
                            Price = 25000m,
                            SKU = "GPU-RTX-4070",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 13,
                            Description = "Yüksek hızlı bellek kiti (2x8GB)",
                            IsActive = true,
                            Name = "RAM 16GB DDR5",
                            Price = 1800m,
                            SKU = "RAM-16-DDR5",
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 14,
                            Description = "Sessiz ve etkili işlemci soğutucusu",
                            IsActive = true,
                            Name = "Soğutucu Fan",
                            Price = 950m,
                            SKU = "FAN-CPU-SLNT",
                            StockQuantity = 220
                        },
                        new
                        {
                            Id = 15,
                            Description = "En yeni işlemciler için ATX anakart",
                            IsActive = true,
                            Name = "Anakart Z790",
                            Price = 9200m,
                            SKU = "MB-Z790-ATX",
                            StockQuantity = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
